version: "3.9"

services:
  db:
    image: postgres:16
    container_name: laundryheroes-db
    environment:
      POSTGRES_USER: laundryheroes
      POSTGRES_PASSWORD: laundryheroes
      POSTGRES_DB: laundryheroes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: laundryheroes-app
    environment:
      SPRING_PROFILES_ACTIVE: "local"
      FIREBASE_SERVICE_ACCOUNT_JSON: ${FIREBASE_SERVICE_ACCOUNT_JSON}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
